language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode9.1
before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
    sudo apt-get update -y;
    sudo apt-get upgrade -y;
    sudo apt-get dist-upgrade -y;
    eval "$(curl -sL https://raw.githubusercontent.com/ryuichis/oclint-cpp-travis-ci-examples/master/oclint-ci-install.sh)";
  fi
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
  - cd ..
  - cp build/compile_commands.json .
  - oclint-json-compilation-database
